insert into author(author_id, first_name, last_name, country) values(1, 'John', 'Steinbeck', 'United States');
insert into author(author_id, first_name, last_name, country) values(2, 'George', 'Orwell', 'United States');
insert into author(author_id, first_name, last_name, country) values(3, 'William', 'Shakespeare', 'England');
insert into author(author_id, first_name, last_name, country) values(4, 'William', 'Golding', 'England');
insert into author(author_id, first_name, last_name, country) values(5, 'Ernest', 'Hemmingway', 'United States');
insert into author(author_id, first_name, last_name, country) values(6, 'Charles', 'Dickens', 'England');
insert into author(author_id, first_name, last_name, country) values(7, 'Alexandre', 'Dumas', 'France');
insert into author(author_id, first_name, last_name, country) values(8, 'Nathaniel', 'Hawthorne', 'United States');
insert into author(author_id, first_name, last_name, country) values(9, 'Erich', 'Gamma', 'United States');
insert into author(author_id, first_name, last_name, country) values(10, 'Leo', 'Tolstoy', 'Russia');
insert into author(author_id, first_name, last_name, country) values(11, 'Ken', 'Kesey', 'Russia');

insert into book(book_id, title, publish_date, page_count, price, author_id) values (1,'Of Mice and Men', '1954-11-08', 230, 11.00,1);
insert into book(book_id, title, publish_date, page_count, price, author_id) values (2,'One Flew Over the Cuckoos Nest', '1973-11-08', 301, 15.00,11);
insert into book(book_id, title, publish_date, page_count, price, author_id) values (3,'For Whom the Bell Tolls', '1932-11-08', 210, 13.00,5);
insert into book(book_id, title, publish_date, page_count, price, author_id) values (4,'War and Peace', '1955-11-21', 400, 15.00,10);
insert into book(book_id, title, publish_date, page_count, price, author_id) values (5,'The Grapes of Wrath', '1955-11-14', 350, 16.00,1);
insert into book(book_id, title, publish_date, page_count, price, author_id) values (6,'Design Patterns', '1996-11-25', 120, 14.00,9);
insert into book(book_id, title, publish_date, page_count, price, author_id) values (7,'A Tale of Two Cities', '1943-11-19', 270, 15.00,6);
insert into book(book_id, title, publish_date, page_count, price, author_id) values (8,'Animal Farm', '1965-06-08', 126, 22.00,2);
insert into book(book_id, title, publish_date, page_count, price, author_id) values (9,'Lord of the Flies', '1973-03-08', 300, 119.00,4);
insert into book(book_id, title, publish_date, page_count, price, author_id) values (10,'Great Expectations', '1878-10-08', 140, 13.66,6);
insert into book(book_id, title, publish_date, page_count, price, author_id) values (11,'The Count of Monte Cristo', '1903-12-08', 160, 22.25,7);
insert into book(book_id, title, publish_date, page_count, price, author_id) values (12,'The Scarlet Letter', '1957-10-08', 170, 16.00,8);
insert into book(book_id, title, publish_date, page_count, price, author_id) values (13,'Hamlet', '1655-11-08', 180, 19.56,3);
insert into book(book_id, title, publish_date, page_count, price, author_id) values (14,'The Old Man and the Sea', '1952-09-08', 190, 23.00,5);
